# Site settings
title: DanHolloran
email: dtholloran@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My adventures on and off of the internetz.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danholloran.me" # the base hostname & protocol for your site
twitter_username: dholloran
github_username:  dholloran
linkedin_username: dholloran
version: 1.0.1

# Handling Reading
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - package.json
  - README.md

# Outputting
permalink: pretty
timezone: America/Chicago
paginate: 10
highlighter: pygments

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-mentions

# Front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Dan Holloran"
